#!/bin/sh

netif_depend() {
	require slaves
}

netif_post_up() {
	ip addr add 0.0.0.0 dev $interface
	ifenslave $interface ${slaves//netif./}
}

netif_pre_down() {
	ifenslave -d $interface ${slaves//netif./}
}
