#!/bin/sh

netif_create() {
	brctl addbr $interface
}

netif_destroy() {
	brctl delbr $interface
}

netif_pre_up() {
	local slave
	if [ -n "$slaves" ]; then
		for slave in ${slaves//netif./}; do
			brctl addif $interface ${slave}
		done
	fi	
	brctl setfd $interface 0 
	for ipnm in $ipaddr $ipaddrs; do
		ip addr add $ipnm dev $interface || die "Couldn't add $ipnm to $interface"
	done
}
